In [27]:
from tensorflow.keras.preprocessing.text import one_hot

In [28]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [29]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [30]:
## Define the vocabulary size
voc_size=10000

In [31]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [32]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1355, 9781, 4099, 2],
 [1355, 9781, 4099, 8821],
 [1355, 8876, 4099, 1856],
 [6596, 7275, 5189, 6531, 2862],
 [6596, 7275, 5189, 6531, 6548],
 [9012, 1355, 1631, 4099, 6072],
 [615, 1856, 4150, 6531]]

In [33]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [34]:
sent_length=8
#if lengths are different  here we use padding

embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1355 9781 4099    2]
 [   0    0    0    0 1355 9781 4099 8821]
 [   0    0    0    0 1355 8876 4099 1856]
 [   0    0    0 6596 7275 5189 6531 2862]
 [   0    0    0 6596 7275 5189 6531 6548]
 [   0    0    0 9012 1355 1631 4099 6072]
 [   0    0    0    0  615 1856 4150 6531]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\shrut\Downloads\Project_resources\simple_rnn_imdb\myenv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [35]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 474ms/step


array([[[-0.03494536,  0.02026676,  0.00312025,  0.03089729,
          0.03362432,  0.00387982,  0.01414287, -0.03095986,
         -0.04806   ,  0.03711675],
        [-0.03494536,  0.02026676,  0.00312025,  0.03089729,
          0.03362432,  0.00387982,  0.01414287, -0.03095986,
         -0.04806   ,  0.03711675],
        [-0.03494536,  0.02026676,  0.00312025,  0.03089729,
          0.03362432,  0.00387982,  0.01414287, -0.03095986,
         -0.04806   ,  0.03711675],
        [-0.03494536,  0.02026676,  0.00312025,  0.03089729,
          0.03362432,  0.00387982,  0.01414287, -0.03095986,
         -0.04806   ,  0.03711675],
        [ 0.01654   ,  0.02330187,  0.02880779,  0.03267861,
          0.03694067, -0.00950267,  0.03401678, -0.03980762,
          0.042712  , -0.01690688],
        [ 0.0063711 ,  0.03584782,  0.0385411 , -0.01287486,
          0.03827772,  0.01443502,  0.02638007,  0.03323822,
         -0.0173664 ,  0.01064317],
        [ 0.01030433, -0.04423332, -0.03621387, -0.0

In [25]:
embedded_docs[0]

array([   0,    0,    0,    0, 1355, 9781, 4099,    2])

In [26]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None